server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:akakumar-gd/config-repo.git
          ignoreLocalSshSettings: false
          default-label: master
          clone-on-start: true