server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: product-service

resilience4j:
  circuitbreaker:
    instances:
      productCB:
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
  timelimiter:
    instances:
      productCB:
        timeoutDuration: 2s
catalog-service:
  url: http://localhost:8081/catalog
inventory-service:
  url: http://localhost:8082/inventory
